name: speech_to_text_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: 0.13.4

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  flutter_launcher_icons: ^0.9.2

  # recording words
  speech_to_text: ^3.1.0

  # launch apps, browser & email
  url_launcher: ^5.7.10

  # copy text to clipboard
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"

flutter:
  uses-material-design: true